<a href="https://colab.research.google.com/github/Mumthaz-Alfan/ICT-ACTIVITY/blob/main/HouseCasestudyprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv('/content/House_Pricing.csv')
df.head()

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,...,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,...,7,1180.0,0,63,0,98178.0,47.5112,-122.257,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,...,7,2170.0,400,67,1991,98125.0,47.7210,-122.319,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,...,6,770.0,0,85,0,98028.0,47.7379,-122.233,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,...,7,1050.0,910,53,0,98136.0,47.5208,-122.393,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,...,8,1680.0,0,31,0,98074.0,47.6168,-122.045,1800.0,7503

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21613 non-null  int64
 1   Date House was Sold                        21613 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21613 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21604 non-null  float64
 6   Lot Area (in Sqft)                         21604 non-null  float64
 7   No of Floors                               21613 non-null  float64
 8   Waterfront View                            21613 non-null  object
 9   No of Times Visited                        2124 non-null   object
 10  Condition of the House                     21613 non-null  object
 11  Overall Grade                              21613 non-null  int64
 12  Area of the House from Basement (in Sqft)  21610 non-null  float64
 13  Basement Area (in Sqft)                    21613 non-null  int64
 14  Age of House (in Years)                    21613 non-null  int64
 15  Renovated Year                             21613 non-null  int64
 16  Zipcode                                    21612 non-null  float64
 17  Latitude                                   21612 non-null  float64
 18  Longitude                                  21612 non-null  float64
 19  Living Area after Renovation (in Sqft)     21612 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21613 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [41]:
df.describe()

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Latitude,Longitude,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
count,2.161300e+04,2.160900e+04,21613.000000,21609.000000,21604.000000,2.160400e+04,21613.000000,21613.000000,21610.000000,21613.000000,21613.000000,21613.000000,21612.000000,21612.000000,21612.000000,21612.000000,21613.000000
mean,4.580302e+09,5.401984e+05,3.370842,2.114732,2079.931772,1.510776e+04,1.494309,7.623467,1788.344193,291.509045,46.994864,84.402258,98077.937766,47.560048,-122.213892,1986.538914,12768.455652
std,2.876566e+09,3.673890e+05,0.930062,0.770138,918.487597,4.142827e+04,0.539989,1.105439,827.982604,442.575043,29.373411,401.679240,53.505425,0.138565,0.140830,685.404255,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,1.000000,290.000000,0.000000,3.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1429.250000,5.040000e+03,1.000000,7.000000,1190.000000,0.000000,21.000000,0.000000,98033.000000,47.470975,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.617500e+03,1.500000,7.000000,1560.000000,0.000000,43.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068825e+04,2.000000,8.000000,2210.000000,560.000000,67.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,10.000000,9410.000000,4820.000000,118.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [42]:
# Count the number of duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [43]:
# Drop the latitude and longitude columns in place
df.drop(columns=['Latitude', 'Longitude'],errors = 'ignore', inplace=True)
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,NaN,Fair,7,1180.0,0,63,0,98178.0,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,NaN,Fair,7,2170.0,400,67,1991,98125.0,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,NaN,Fair,6,770.0,0,85,0,98028.0,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,NaN,Excellent,7,1050.0,910,53,0,98136.0,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,NaN,Fair,8,1680.0,0,31,0,98074.0,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,NaN,Fair,8,1530.0,0,9,0,98103.0,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,NaN,Fair,8,2310.0,0,4,0,98146.0,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,NaN,Fair,7,1020.0,0,9,0,98144.0,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,NaN,Fair,8,1600.0,0,14,0,98027.0,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,NaN,Fair,7,1020.0,0,10,0,98144.0,1020.0,1357

In [44]:
# Check unique values in 'Waterfront View'
print("Unique values in Waterfront View:")
print(df['Waterfront View'].value_counts(dropna=False))

print("\n" + "="*40 + "\n")

# Check unique values in 'No of Times Visited'
print("Unique values in No of Times Visited:")
print(df['No of Times Visited'].value_counts(dropna=False))

Unique values in Waterfront View:
Waterfront View
No     21450
Yes      163
Name: count, dtype: int64

========================================

Unique values in No of Times Visited:
No of Times Visited
NaN       19489
Twice       963
Thrice      510
Once        332
Four        319
Name: count, dtype: int64

In [45]:
# Replace NaN values with 'None'
df['No of Times Visited'].fillna('None', inplace=True)
df

/tmp/ipykernel_1413/1867110084.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['No of Times Visited'].fillna('None', inplace=True)

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,No,None,Fair,7,1180.0,0,63,0,98178.0,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,No,None,Fair,7,2170.0,400,67,1991,98125.0,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,No,None,Fair,6,770.0,0,85,0,98028.0,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,No,None,Excellent,7,1050.0,910,53,0,98136.0,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,No,None,Fair,8,1680.0,0,31,0,98074.0,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,No,None,Fair,8,1530.0,0,9,0,98103.0,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,No,None,Fair,8,2310.0,0,4,0,98146.0,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,No,None,Fair,7,1020.0,0,9,0,98144.0,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,No,None,Fair,8,1600.0,0,14,0,98027.0,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,No,None,Fair,7,1020.0,0,10,0,98144.0,1020.0,1357

In [46]:
# Convert to binary numeric values
df['Waterfront View'] = df['Waterfront View'].map({'No': 0, 'Yes': 1})
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,0,None,Fair,7,1180.0,0,63,0,98178.0,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,0,None,Fair,7,2170.0,400,67,1991,98125.0,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,0,None,Fair,6,770.0,0,85,0,98028.0,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,0,None,Excellent,7,1050.0,910,53,0,98136.0,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,0,None,Fair,8,1680.0,0,31,0,98074.0,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,0,None,Fair,8,1530.0,0,9,0,98103.0,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,0,None,Fair,8,2310.0,0,4,0,98146.0,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,0,None,Fair,7,1020.0,0,9,0,98144.0,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,0,None,Fair,8,1600.0,0,14,0,98027.0,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,0,None,Fair,7,1020.0,0,10,0,98144.0,1020.0,1357

In [47]:
# Show columns with missing values and their counts
missing_data = df.isnull().sum()
print(missing_data[missing_data > 0])

Sale Price                                   4
No of Bathrooms                              4
Flat Area (in Sqft)                          9
Lot Area (in Sqft)                           9
Area of the House from Basement (in Sqft)    3
Zipcode                                      1
Living Area after Renovation (in Sqft)       1
dtype: int64

In [48]:
# Filling each column
fill_values = {
    'Sale Price': df['Sale Price'].median(),
    'No of Bathrooms': df['No of Bathrooms'].median(),
    'Flat Area (in Sqft)': df['Flat Area (in Sqft)'].median(),
    'Lot Area (in Sqft)': df['Lot Area (in Sqft)'].median(),
    'Area of the House from Basement (in Sqft)': df['Area of the House from Basement (in Sqft)'].median(),
    'Zipcode': df['Zipcode'].median(),
    'Living Area after Renovation (in Sqft)': df['Living Area after Renovation (in Sqft)'].median(),
    'Waterfront View': 0
}

# Apply all the fills at the same time
df.fillna(value=fill_values, inplace=True)

# Verify no missing values remain
print("Total remaining missing values:", df.isnull().sum().sum())
df

Total remaining missing values: 0

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,3,1.00,1180.0,5650.0,1.0,0,None,Fair,7,1180.0,0,63,0,98178.0,1340.0,5650
1,6414100192,14 December 2017,538000.0,3,2.25,2570.0,7242.0,2.0,0,None,Fair,7,2170.0,400,67,1991,98125.0,1690.0,7639
2,5631500400,15 February 2016,180000.0,2,1.00,770.0,10000.0,1.0,0,None,Fair,6,770.0,0,85,0,98028.0,2720.0,8062
3,2487200875,14 December 2017,604000.0,4,3.00,1960.0,5000.0,1.0,0,None,Excellent,7,1050.0,910,53,0,98136.0,1360.0,5000
4,1954400510,15 February 2016,510000.0,3,2.00,1680.0,8080.0,1.0,0,None,Fair,8,1680.0,0,31,0,98074.0,1800.0,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,3,2.50,1530.0,1131.0,3.0,0,None,Fair,8,1530.0,0,9,0,98103.0,1530.0,1509
21609,6600060120,15 February 2016,400000.0,4,2.50,2310.0,5813.0,2.0,0,None,Fair,8,2310.0,0,4,0,98146.0,1830.0,7200
21610,1523300141,14 June 2017,402101.0,2,0.75,1020.0,1350.0,2.0,0,None,Fair,7,1020.0,0,9,0,98144.0,1020.0,2007
21611,291310100,15 January 2016,400000.0,3,2.50,1600.0,2388.0,2.0,0,None,Fair,8,1600.0,0,14,0,98027.0,1410.0,1287
21612,1523300157,14 October 2017,325000.0,2,0.75,1020.0,1076.0,2.0,0,None,Fair,7,1020.0,0,10,0,98144.0,1020.0,1357

In [49]:
from sklearn.preprocessing import StandardScaler

# 1. Identify all numerical columns automatically
numerical_cols = df.select_dtypes(include=['number']).columns.tolist()

# 2. Exclude 'Sale Price' and 'ID' from scaling
cols_to_scale = [col for col in numerical_cols if col not in ['Sale Price', 'ID']]

# 3. Initialize and apply StandardScaler
scaler = StandardScaler()
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

# 4. View a quick preview of the scaled dataset
print("Scaled features successfully!")
df[cols_to_scale].head()

Scaled features successfully!

,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,-0.087173,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870228,-0.943328,-0.260715
1,-0.398737,0.175628,0.533757,-0.189832,0.936506,-0.087173,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879629,-0.432658,-0.187868
2,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,-0.087173,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933352,1.070173,-0.172375
3,0.676485,1.149589,-0.130528,-0.243962,-0.915427,-0.087173,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085225,-0.914147,-0.284522
4,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,-0.087173,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073588,-0.272161,-0.192849

In [50]:
df

,ID,Date House was Sold,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,14 October 2017,221900.0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,-0.087173,None,Fair,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870228,-0.943328,-0.260715
1,6414100192,14 December 2017,538000.0,-0.398737,0.175628,0.533757,-0.189832,0.936506,-0.087173,None,Fair,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879629,-0.432658,-0.187868
2,5631500400,15 February 2016,180000.0,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,-0.087173,None,Fair,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933352,1.070173,-0.172375
3,2487200875,14 December 2017,604000.0,0.676485,1.149589,-0.130528,-0.243962,-0.915427,-0.087173,None,Excellent,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085225,-0.914147,-0.284522
4,1954400510,15 February 2016,510000.0,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,-0.087173,None,Fair,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073588,-0.272161,-0.192849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,14 May 2017,360000.0,-0.398737,0.500282,-0.598793,-0.337373,2.788439,-0.087173,None,Fair,0.340626,-0.312005,-0.658681,-1.293542,-0.210128,0.468438,-0.666107,-0.412381
21609,6600060120,15 February 2016,400000.0,0.676485,0.500282,0.250619,-0.224333,0.936506,-0.087173,None,Fair,0.340626,0.630126,-0.658681,-1.463768,-0.210128,1.272131,-0.228390,-0.203946
21610,1523300141,14 June 2017,402101.0,-1.473959,-1.772294,-1.154179,-0.332086,0.936506,-0.087173,None,Fair,-0.564013,-0.928014,-0.658681,-1.293542,-0.210128,1.234750,-1.410227,-0.394141
21611,291310100,15 January 2016,400000.0,-0.398737,0.500282,-0.522564,-0.307025,0.936506,-0.087173,None,Fair,0.340626,-0.227455,-0.658681,-1.123316,-0.210128,-0.952043,-0.841194,-0.420511
21612,1523300157,14 October 2017,325000.0,-1.473959,-1.772294,-1.154179,-0.338701,0.936506,-0.087173,None,Fair,-0.564013,-0.928014,-0.658681,-1.259497,-0.210128,1.234750,-1.410227,-0.417948

In [51]:


#  categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print("Identified Categorical Columns:", categorical_cols)

#  Apply Ordinal Encoding (Label Encoding with custom logical order)
# Since 'No of Times Visited' and 'Condition of the House' are ordinal,  map them to ranks
visit_mapping = {'None': 0, 'Once': 1, 'Twice': 2, 'Thrice': 3, 'Four': 4}
df['No of Times Visited'] = df['No of Times Visited'].map(visit_mapping)

condition_mapping = {'Bad': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4}
df['Condition of the House'] = df['Condition of the House'].map(condition_mapping)

# One-Hot Encoding for Nominal Categories

df_cleaned = df.drop(columns=['Date House was Sold'], errors='ignore')
df_encoded = pd.get_dummies(df_cleaned, drop_first=True)

# clean encoded dataset
print("\nFinal Processed Dataset Shape:", df_encoded.shape)
df_encoded.head()

Identified Categorical Columns: ['Date House was Sold', 'No of Times Visited', 'Condition of the House']

Final Processed Dataset Shape: (21613, 18)

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,221900.0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,-0.087173,0,2.0,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870228,-0.943328,-0.260715
1,6414100192,538000.0,-0.398737,0.175628,0.533757,-0.189832,0.936506,-0.087173,0,2.0,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879629,-0.432658,-0.187868
2,5631500400,180000.0,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,-0.087173,0,2.0,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933352,1.070173,-0.172375
3,2487200875,604000.0,0.676485,1.149589,-0.130528,-0.243962,-0.915427,-0.087173,0,4.0,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085225,-0.914147,-0.284522
4,1954400510,510000.0,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,-0.087173,0,2.0,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073588,-0.272161,-0.192849

In [52]:
# 1. Select the key original numeric features to clean
outlier_features = ['Sale Price', 'Flat Area (in Sqft)', 'Lot Area (in Sqft)']

print("Rows before:", len(df_encoded))

# 2. Loop through each column, calculate bounds, and filter out outliers
for col in outlier_features:
    Q1 = df_encoded[col].quantile(0.25)
    Q3 = df_encoded[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Keep only the rows within the typical range
    df_encoded = df_encoded[(df_encoded[col] >= lower_bound) & (df_encoded[col] <= upper_bound)]

print("Rows after:", len(df_encoded))
df_encoded.head()

Rows before: 21613
Rows after: 18023

,ID,Sale Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,Waterfront View,No of Times Visited,Condition of the House,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),Renovated Year,Zipcode,Living Area after Renovation (in Sqft),Lot Area after Renovation (in Sqft)
0,7129300520,221900.0,-0.398737,-1.447640,-0.979940,-0.228268,-0.915427,-0.087173,0,2.0,-0.564013,-0.734756,-0.658681,0.544898,-0.210128,1.870228,-0.943328,-0.260715
1,6414100192,538000.0,-0.398737,0.175628,0.533757,-0.189832,0.936506,-0.087173,0,2.0,-0.564013,0.461025,0.245141,0.681079,4.746678,0.879629,-0.432658,-0.187868
2,5631500400,180000.0,-1.473959,-1.447640,-1.426426,-0.123244,-0.915427,-0.087173,0,2.0,-1.468651,-1.229979,-0.658681,1.293892,-0.210128,-0.933352,1.070173,-0.172375
3,2487200875,604000.0,0.676485,1.149589,-0.130528,-0.243962,-0.915427,-0.087173,0,4.0,-0.564013,-0.891778,1.397515,0.204446,-0.210128,1.085225,-0.914147,-0.284522
4,1954400510,510000.0,-0.398737,-0.149026,-0.435445,-0.169600,-0.915427,-0.087173,0,2.0,0.340626,-0.130826,-0.658681,-0.544548,-0.210128,-0.073588,-0.272161,-0.192849

In [53]:
from sklearn.model_selection import train_test_split

# 1. Separate features (X) and target variable (y)
X = df_encoded.drop(columns=['Sale Price'])
y = df_encoded['Sale Price']

# 2. Split into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify the shapes
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")

Training features shape: (14418, 17)
Testing features shape: (3605, 17)